artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: C:\Users\aniyant\python\Ineuron\Projects\Adult Census Income Prediction\adult.csv
  local_data_file: artifacts/data_ingestion/data.csv
  #unzip_dir: artifacts/data_ingestion