artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://drive.google.com/uc?id=1unOSQaW-Sy5gkK0jpDubCFFie4NuN02e'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv
  
data_validation:
  root_dir: artifacts/data_validation
  schema_file_path: configs/schema.yaml
  train_data_file_path: artifacts/data_ingestion/train.csv
  test_data_file_path: artifacts/data_ingestion/test.csv
  report_file_path: artifacts/data_validation/report.json
  report_page_file_path: artifacts/data_validation/report.html

data_transformation:
  root_dir: artifacts/data_transformation
  schema_file_path: configs/schema.yaml
  train_data_file_path: artifacts/data_ingestion/train.csv
  test_data_file_path: artifacts/data_ingestion/test.csv
  transformed_train_path: artifacts/data_transformation/train.npz
  transformed_test_path: artifacts/data_transformation/test.npz
  preprocessed_object_file_path: artifacts/data_transformation/preprocessed.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  transformed_train_path: artifacts/data_transformation/train.npz
  transformed_test_path: artifacts/data_transformation/test.npz
  preprocessed_pkl_file_path: artifacts/data_transformation/preprocessed.pkl
  model_config_file_path: configs/model.yaml
  trained_model_file_path: artifacts/model_trainer/model.pkl
  base_accuracy: 0.6
  model_config_file_path: configs/model.yaml
