columns:
  age: int64
  workclass: object
  fnlwgt: int64
  education: object
  education-num: int64
  marital-status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital-gain: int64
  capital-loss: int64
  hours-per-week: int64
  country: object
  salary: object

target_column: salary

number_of_cols: 15

numerical_columns:
  - age
  - fnlwgt
  - capital-gain
  - capital-loss

categorical_columns:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - hours-per-week
  - country